### ISSUE TITLE
Node Red 

### ISSUE THREAD

**Issue by manueldiasmanuel** [koochyrat/comfort2#3]
How could i  use the same solution  in node-red ?    Would  be possible to adjust de code ? 

Thanks,

M D

**Comment by koochyrat** [comment]
Have node-red talk to a MQTT broker. MQTT then talks to comfort2. I've never tried it but it should be possible since MQTT is a standard interface.

**Comment by manueldiasmanuel** [comment]
I have now node-red talking with comfort2 with MQTT. The result is very good.
Really amazing,  great job !

Thanks.

**Comment by auredor** [comment]
@manueldiasmanuel Could you please share your node-red flow? Thanks

**Comment by manueldiasmanuel** [comment]
[FlowMQTTComfort2.txt](https://github.com/koochyrat/comfort2/files/2899658/FlowMQTTComfort2.txt)

Here you have the node-red flow i used for test.  Let me know if you need something else.

**Comment by auredor** [comment]
Thank I will have a look.
